typography_spectrum: 0.9592177984304726
color:
  brandStrength: 0.7658615433610976
  lightness: 0.6093828429002315
  saturation: 0.24194435006938875
  rhythmicContrast: 0.406426158035174
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.5482974518090487
name: Christian Kinnard
title: Christian Kinnard • Editor
description: TV • Film Editor
